### ISSUE TITLE
Space Pin interpolation should work vertically, too, but only does so horizontally

### ISSUE THREAD

**Issue by BattleWorm** [microsoft/MixedReality-WorldLockingTools-Unity#64] opened 2020-07-01 10:32 UTC
I'm trying to use Space Pins to align the size of an MR space with the exact real-world space's size determined beforehand using a laser ruler.
However, the virtual objects are not placed on just one floor, but on several floors in a building - and I need the Space Pins to also correctly align the vertical distance of the floors with the laser ruler measurement.

When trying to achieve this with SpacePins right now, the result is this:
![SpacePinningProblem](https://user-images.githubusercontent.com/1758939/86226510-11670080-bb8c-11ea-9164-1dff58452935.png)

The pinned scene shifts to the ground floor alignment when the user is standing above the ground floor SpacePin (or more precisely, is closer to the the SpacePin _horizontally_), whereas the scene uses the top floor alignment when the user is standing above the top floor SpacePin (is closer to that SpacePin _horizontally_).
When the two SpacePins are roughly above each other with just a minor horizontal offset, this means that the aligned scene wildly jumps in height when the user is about equally close to the two SpacePins horizontally.

Therefore, it should be possible align the pinned scene also when moving vertically between SpacePins, not just horizontally. That is, the user's distance to the SpacePins that's used for interpolation should take the Y coordinate into account.

**Comment by fast-slow-still** [comment] 2020-07-01 11:00
You are correct that currently the interpolation is entirely driven by the user's horizontal position. This is also why pins vertically aligned are not supported at all.

Supporting at least multi-level scenarios, and ideally full 3D volumes, is a high priority future work item. But it is non-trivial.

The only current way of doing that which I am aware of is to set different SaveFileName's for different floors, and manually Save and Load appropriately. Something like:
OnEnterRoom(string roomName)
    ClearAllSpacePins()
    alignmentManager.SaveFileName = roomName
    alignmentManager.Load()

Agreed that this isn't very nice.

**Comment by BattleWorm** [comment] 2020-07-01 11:28
Thanks for your quick feedback.

Unfortunately, using independent pinned spaces for different floors is not an option for me, as I need both floors in the same context, i.e. in the same pinned space. Otherwise, my app doesn't make any sense.

I can imagine that an interpolation in three dimensions is difficult to get right.
Would it be easier to do the interpolation based _solely_ on the vertical offset to the SpacePins? Because in my scenario, that would be perfectly sufficient.

**Comment by fast-slow-still** [comment] 2020-07-01 13:10
The interpolation is the second half the problem. The first part of the problem is to process the set of 3D points (SpacePin locations) into an efficient, query-able, linearly interpolating data structure. That only needs to happen when the set of 3D points changes (SpacePin(s) added or removed), so can be relatively slow (but a small fraction of a frame).

Then the interpolation, based on head position, needs to happen each frame, so must me extremely efficient ( < 1m).

Simplifying the problem by projecting it onto the horizontal plane has obvious benefits, and equally obvious limitations.

If I'm understanding your application's requirements correctly, then to convert the projection onto the horizontal plane into an equally simplifying projection onto a vertical plane (e.g. XY plane), would be a trivial modification to the SimpleTriangulator class, which implements ITriangulator (see https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Temp/api/Microsoft.MixedReality.WorldLocking.Core.Triangulator.SimpleTriangulator.html).

If you implemented that as something like SimpleTriangulatorXY, then using that instead of the default could be instantiated by simply replacing the `new Triangulator.SimpleTriangulator()` with `new SimpleTriangulatorXY()` in AlignmentManager.cs (with trivial UX controls later if it turned out to be useful).  

If you are interested in pursuing that route, let me know and I would be happy to assist.

**Comment by BattleWorm** [comment] 2020-07-01 13:19
Ah, nice! If it's as simple as that, I'd certainly love to try it out. 
In my specific case, I might be able to simplify the interpolation even more by reducing it to only the Y axis.

**Comment by fast-slow-still** [comment] 2020-07-01 13:33
Very interesting. Yes, that's an excellent point. You might want to ignore SimpleTriangulator entirely and just implement ITriangulator on the Y-axis.

Again, feel free to ping me for clarifications, either on this issue or via my email (on my profile). And if you don't wind up needing any assistance, I'd be interested in hearing that too.

**Comment by zantiu** [comment] 2020-07-01 22:50
Interesting I didn't notice yet that  there was no vertical interpolation, but our application will also not work without this.

**Comment by fast-slow-still** [comment] 2020-07-02 08:44
I'm not sure I understand this comment. The interpolation is computed by the ITriangulator in Find(Vector3 pos). The three pose weights returned in the interpolant are applied by the AlignmentManager blindly. If they are computed strictly by height in the Triangulator which you supply, then the interpolation will be strictly height based.

I don't want to take the fun out of it for you by telling how I would do it, but if you asked I would of course be happy to share my approach.

Again, feel free to move this to email, as it is getting a bit specific for a general issue or work item.

**Comment by BattleWorm** [comment] 2020-07-02 09:07
Alright, got the purely vertical interpolation working by implementing a "TriangulatorY" and setting it on the AlignmentManager instead of the SimpleTriangulator. Works nicely - SpacePin alignment now transitions between the two floors depending on my head height in space, without taking X and Z into account. So, thanks a bunch for pointing me in the right direction here!

One thing that still bothers me, though, is that I'm still observing a drift of the upper floor SpacePin over time. I'm setting both SpacePins shortly after the start of the app, including a visual marker to highlight the pinned position on the floor at each story. At the time, the pins are perfectly level with the floor when I'm close to them. After going back to the lower floor and doing some work in the app there for a few minutes, however, the upper landing pin starts to drift, and once I get back to the upper floor, I can see that the visual marker is now several centimeters below floor level.
I suppose this is a topic for another issue, right?

**Comment by fast-slow-still** [comment] 2020-07-02 09:19
Glad to hear you have the vertical interpolation working!

Yes, the drift issue is quite of interest, that certainly should not be happening. Please do submit a separate issue for that, and include the WLT version you are using, the Frozen World Engine plugin version, and the hardware you are running on. I have a general idea of repro steps, but great if you could lay them out explicitly in the new issue. 

Also, the output of your Unity log and FW logs as documented [here](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/Contributing.html#reporting-a-bug).

Also, great if you can include your Triangulator code for me to fully repro, but not essential if it is awkward regarding licensing/IP/etc. 

Thanks!

**Comment by fast-slow-still** [comment] 2020-07-02 13:12
Closing this to take on the remaining issue #65 .

Feel free to reopen this if there are issues remaining related to the Y-axis interpolation.

I will open a separate issue for a general 3D volume interpolation.

**Closed** 2020-07-02 13:12 UTC
