### ISSUE TITLE
Spatial mapping appears in the incorrect location

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedReality-WorldLockingTools-Unity#103] opened 2020-12-09 06:57 UTC
I have an issue where the anchors appear stable, but the spatial mapping exhibits some strange behaviour. This occurs in the `WorldLockingBasic` example (adapted to use the XRSDK) as well as an internal sample.

The spatial mapping appears stable for a few seconds, then begins slowly drifting, then extremely drifting. The anchors remain stable the entire time. Here's a video demonstrating this: https://drive.google.com/file/d/1-U0Bj8Gn3og2gPxtg_2PWbb7MVLvRq_E/view?usp=sharing

I haven't found much discussion of spatial mapping aside from [FrozenSpatialMapping](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Temp/api/Microsoft.MixedReality.WorldLocking.Tools.FrozenSpatialMapping.html), where it states:
> This is unnecessary when using MRTK's spatial mapping, which provides this and other enhancements over the native spatial mapping.

In device portal, the spatial mesh appears as normal.

### Steps to reproduce:
1. Clone latest master https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/commit/8333fcedf57cb4d2c649981cbebc53f040e5f9d0
2. Open with Unity 2019.4.16f1 (performs project upgrade)
3. Import XR Plugin Management (3.2.17) via UPM
4. Import Windows XR Plugin (2.4.1) via UPM and enable for UWP in XR Plugin Management
5. Open scene WorldLocking.Examples/Scenes/WorldLockingBasic
6. Change the MRTK profile to DefaultXRSDKConfigurationProfile
7. Change the WorldLockingManager ARSubsystem to XRSDK
8. Build with scene WorldLocking.Examples/Scenes/WorldLockingBasic configured for HoloLens>ARM64
9. Deploy to Device with Visual Studio (Release ARM64)

(Build runs correctly)

10. **Replace MRTK 2.4.0 with MRTK 2.5.1**

(Build exhibits strange behaviour described above)

Subsequently I suspect this is related to the MRTK version upgrade.

**Comment by camnewnham** [comment] 2020-12-10 00:01
I'm having some trouble verifying that this is the cause. 

Building this repo (master) in U2019.4.16f1 with no other changes other than to the profiles/XRSDK seems to work as expected.
Modifying the project (i.e. MRTK upgrade as described above) seems to break it and cause this issue.

Attempting to match the configuration (including a copy+paste of the exact MRTK from master) in an existing project also causes this issue.

![image](https://user-images.githubusercontent.com/19278856/101703522-d40d8400-3ad6-11eb-9fe3-e4d4acf4a64c.png)

![image](https://user-images.githubusercontent.com/19278856/101703587-f7d0ca00-3ad6-11eb-9db7-9dde669a6d3b.png)


![image](https://user-images.githubusercontent.com/19278856/101703628-0f0fb780-3ad7-11eb-8d6e-275885124246.png)

Am I missing a critical dependency relationship here? Or is something being cached in an unexpected manner? I have turned off Save/Load, and uninstalled, and cleared the Library folder:

**Comment by fast-slow-still** [comment] 2020-12-10 12:01
This sounds just like this MRTK issue I found and fixed recently. #8920

To verify that you have the fix, could you open Assets\MRTK\Providers\XRSDK\GenericXRSDKSpatialMeshObserver.cs, and verify that all reference to the class PlayspaceAdapter has been removed? (You can text search for Adapter in that file and it should come up as not found.)

Thanks!

**Comment by fast-slow-still** [comment] 2020-12-10 12:11
Ah, I just saw a comment above. Excellent write-up, by the way, it is very much appreciated that you take the time to be clear about the issues.

If I am reading your comments correctly, the problem happens when you update to MRTK v2.5.1. That makes sense. The fix that I implemented above is in the latest mrtk_development branch (so will be in the next release), but didn't make it into the v2.5.1 release.

If you want to recreate the fix locally onto your v2.5.1 branch, it's actually a very simple fix. Just remove the creation and addition of the `GameObject anchorHolder` in `RequestMesh()`. That makes the declaration of the PlayspaceAdapter class superfluous. You can delete it for cleanliness or leave it.

**Comment by fast-slow-still** [comment] 2021-01-04 17:16
Let me know if the fix to the issue linked above doesn't resolve the problem.

**Closed** 2021-01-04 17:16 UTC

**Comment by folocam** [comment] 2021-02-03 05:42
Thanks, the issue is resolved with your proposed changes. Apologies for the delay in getting back to you.

It looks like it will be included in the MRTK 2.6 milestone so hopefully it will be included then :)

**Comment by camnewnham** [comment] 2021-02-03 05:43
Thanks, the issue is resolved with your proposed changes. Apologies for the delay in getting back to you.

It looks like it will be included in the MRTK 2.6 milestone so hopefully it will be included then :)
